on: pull_request

permissions:
  pull-requests: write

jobs:
  check-backward-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup buf cli
        uses: bufbuild/buf-setup-action@v1.50.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint proto files 
        uses: bufbuild/buf-lint-action@v1
        with:
          input: 'contracts/proto'

      - name: Check backward compatibility
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/zhunismp/mmp-contract.git#branch=master,,subdir=contracts/proto'
          input: 'contracts/proto'

      